[project]
name = "dunc"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[project.scripts]
dunc = "dunc.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
